---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: destroyed-symlinks
          - id: detect-private-key
          - id: check-ast
          - id: check-case-conflict
          - id: debug-statements
    - repo: https://codeberg.org/frnmst/md-toc
      rev: 8.1.4
      hooks:
          - id: md-toc
            args: [-s7, -c, -p, github, -l6]
    - repo: https://github.com/pecigonzalo/pre-commit-shfmt
      rev: v2.1.0
      hooks:
          - id: shell-fmt
            args:
                - -i
                - '2'
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.8.0
      hooks:
          - id: shellcheck
            args:
                - -x
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.23.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint
                - babel-eslint
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.27.1
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/erikogan/prevent-submodule-regression
      rev: v0.1.2
      hooks:
          - id: prevent-submodule-regression
