---
repos:
    - repo: https://github.com/pecigonzalo/pre-commit-shfmt
      sha: master
      hooks:
          - id: shell-fmt
            args:
                - -i
                - '2'
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.8.0
      hooks:
          - id: shellcheck
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.23.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint
                - babel-eslint
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.27.1
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
