fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: [--maxkb=1000]
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: check-ast
  - id: check-case-conflict
  - id: debug-statements
  - id: check-json
  - id: pretty-format-json
    args:
    - --autofix
    - --no-sort-keys
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: mixed-line-ending
    args: [--fix=lf]

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
  - id: terraform-fmt
  - id: terraform-validate
  - id: tflint
  - id: helmlint
  - id: shellcheck

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.1.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
  - id: yamllint
    args: [-c=.yamllint.yaml]

- repo: https://codeberg.org/frnmst/md-toc
  rev: 8.2.3
  hooks:
  - id: md-toc
    args: [-s30, -c, -p, github, -l6]

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: forbid-binary
    exclude: >
      (?x)^(
        docs/MakefileFlow.png
      )$
  - id: shfmt
    args:
    - -i
    - '2'
  - id: shellcheck
    args:
    - -x

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v9.0.0-beta.1
  hooks:
  - id: eslint
    additional_dependencies:
    - eslint
    - babel-eslint

- repo: https://github.com/erikogan/prevent-submodule-regression
  rev: v0.1.2
  hooks:
  - id: prevent-submodule-regression

ci:
  skip: [shfmt, shellcheck]
