version: "3"

tasks:
  install:
    desc: Install dotfiles using dotfiles.sh
    dir: ./scripts
    env:
      DOTFILES_DIR: ${HOME}/dotfiles # change this
    cmds:
    - V={{.V}} dotfiles.sh
    vars:
      V: "1"
