version: "3"

tasks:
  install:
    desc: Install dotfiles using dotfiles.sh
    dir: ./scripts
    env:
      DOTFILES_DIR: {? {.TaskDir: ''} : ''}
    cmds:
    - V={{.V}} dotfiles.sh
    vars:
      V: "1"
